name: Build and Create PR

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Configure .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'ga'
      
      - name: Install .NET 8 Runtime
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-runtime-8.0 aspnetcore-runtime-8.0 dotnet-sdk-8.0
      
      - name: Allowing sh to execute
        run: 

      - name: Publish
        run: |
          chmod +x app/publish-native-aot.sh
          sh app/publish-native-aot.sh

  open-pr-to-develop:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Create PR
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "develop"
          pr_label: "feature, automated pr"
          pr_title: "PR Created automatically from ${{ github.ref }} to develop"
