name: Build and Create PR

on:
  push:
    branches:
      - 'feature/*'
      - 'hotfix/*'

jobs:
  build-app:
    runs-on: ubuntu-latest

    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Configure .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'ga'
      
      - name: Install .NET 8 Runtime
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-runtime-8.0 aspnetcore-runtime-8.0 dotnet-sdk-8.0
     
      - name: Publish
        run: |
          chmod +x app/publish-native-aot.sh
          sh app/publish-native-aot.sh
    
  terraform-validate: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "^1.3.7"
            terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1
       
      - name: Terraform plan
        run: |
          chmod +x infra/scripts/terraform-plan.sh
          sh infra/scripts/terraform-plan.sh

  open-pr-to-develop:
    runs-on: ubuntu-latest
    needs: 
      - build-app
      - terraform-validate

    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      
      - name: Configure GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Validate if PR exists
        id: check_pr
        run: |
          IS_PR_EXISTS=$(gh pr list --base develop --head ${{ github.ref_name }} --json number --jq '.[0].number')
          if [[ -n "$IS_PR_EXISTS" ]]; then
            echo "PR already exists: #$IS_PR_EXISTS"
            echo "skip=true" >> $GITHUB_ENV
          fi

      - name: Creating Pull Request to develop
        if: env.skip != 'true'
        run: |
          gh pr create \
            --base develop \
            --head ${{ github.ref_name }} \
            --title "🚀 Auto PR from `${{ github.ref_name }}` to `develop`" \
            --body "This PR was created automatically via GitHub Actions." \
            --label "auto-pr, needs-review"
