name: Publish

on:
    push:
      branches:
        - 'master'

jobs:
    terraform-deploy:
        runs-on: ubuntu-latest
        container:
          image: amazonlinux:2023
        steps:
            - name: Install dependencies
              run: yum install -y gcc glibc glibc-devel dotnet-sdk-8.0 tar gzip
              
            - name: Configure .NET 8
              uses: actions/setup-dotnet@v3
              with:
                dotnet-version: '8.0.x'
                dotnet-quality: 'ga'

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: "^1.3.7"
                  terraform_wrapper: false

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: sa-east-1
            
            - name: Code checkout
              uses: actions/checkout@v4

            - name: Deploy
              run: |
                chmod +x infra/scripts/terraform-deploy.sh
                sh infra/scripts/terraform-deploy.sh